services:
  mongo:
    image: mongo:latest
    container_name: storeAPI
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/app/data

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  python:
    build:
      context: .              #current folder ./storeAPI
      dockerfile: Dockerfile
    container_name: mypython
    ports:
      - "5000:5000"            # Expose Flask app
    volumes:
      - ./app:/app            # contains /data folder
    working_dir: /app
    depends_on:
      - mongo
    # command: python app.py       # start flask automatically when >> docker compose up

volumes:
  mongodb_data: