version: "3.8"

services:
  backend:
    build: ./backend
    container_name: soundsync-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: soundsync-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    ports:
      - "8081:8081"           # ou "8082:8081" pour éviter le cache du navigateur
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    depends_on:
      - mongo
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: soundsync-redis
    ports:
      - "6379:6379"

  frontend:
    image: node:20
    container_name: soundsync-frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:5173"
    depends_on:
      - backend

  

volumes:
  mongo_data:
